#!/bin/bash

CONTAINER_NAME="localize-app_dev"

if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
    # if the container is running, exec into it
    docker exec -it $CONTAINER_NAME bash
elif [ "$(docker ps -aq -f status=exited -f name=$CONTAINER_NAME)" ]; then
    # if the container exists but stopped, start and exec into it
    docker start $CONTAINER_NAME
    docker exec -it $CONTAINER_NAME bash
else
    # if the container does not exist, create and start it
    docker run \
     -d \
     -it \
     -p 3000:3000 \
     -v "$(pwd):$(pwd)" -w "$(pwd)" \
     --name $CONTAINER_NAME \
    node \
        tail -f /dev/null

    docker exec -it $CONTAINER_NAME npm install
    docker exec -it $CONTAINER_NAME bash
fi